#!/bin/zsh
#
# launch_cluster.sh — start the 2-node MiniMax-M3 cluster via mlx.launch
#
# Copy .env.example to .env.local and fill in your own hostnames, model path,
# RDMA devices, memory limits, and public endpoint before starting.
#
set -euo pipefail

SCRIPT_DIR="${0:A:h}"
if [[ -f "$SCRIPT_DIR/.env.local" ]]; then
  source "$SCRIPT_DIR/.env.local"
elif [[ -f "$SCRIPT_DIR/m3_cluster.env" ]]; then
  source "$SCRIPT_DIR/m3_cluster.env"
elif [[ -f "$SCRIPT_DIR/.env" ]]; then
  source "$SCRIPT_DIR/.env"
fi

CLUSTER="${M3_CLUSTER_DIR:-$SCRIPT_DIR}"
PYTHON="$CLUSTER/bin/mlx-python"
LAUNCHER="$CLUSTER/run_with_watchdog.py"
MLX_LAUNCH="${M3_MLX_LAUNCH:-/Library/Frameworks/Python.framework/Versions/3.14/bin/mlx.launch}"
MODEL="${MLX_M3_MODEL:-mlx-community/MiniMax-M3-4bit}"
MODEL_ID="${MLX_M3_MODEL_ID:-mlx-community/MiniMax-M3-4bit}"
if [[ -n "${MLX_M3_PROMPT_CACHE_THINKING_MODE:-}" ]]; then
  THINKING_CACHE_MODE="$MLX_M3_PROMPT_CACHE_THINKING_MODE"
elif [[ "${MLX_M3_PROMPT_CACHE_THINKING:-0}" == "1" ]]; then
  THINKING_CACHE_MODE="visible"
else
  THINKING_CACHE_MODE="off"
fi
DIRECT_HOSTS="${M3_MLX_HOSTS_DIRECT:-127.0.0.1,worker.local}"
FALLBACK_HOSTS="${M3_MLX_HOSTS_FALLBACK:-$DIRECT_HOSTS}"
HOSTFILE="${M3_HOSTFILE:-/private/tmp/m3_mlx_hosts.json}"
BACKEND="${M3_MLX_BACKEND:-jaccl}"
LAUNCH_HOST_ARGS=()
RANK1_DIRECT_SSH="${M3_RANK1_DIRECT_SSH:-worker.local}"
RANK1_FALLBACK_SSH="${M3_RANK1_FALLBACK_SSH:-${M3_RANK1_TAILSCALE_SSH:-}}"
RANK1_SSH="$RANK1_DIRECT_SSH"
RANK0_DATA_IP="${M3_RANK0_DATA_IP:-primary.local}"
RANK1_DATA_IP="${M3_RANK1_DATA_IP:-worker.local}"
RANK0_RDMA="${M3_RANK0_RDMA:-}"
RANK1_RDMA="${M3_RANK1_RDMA:-}"
RANK0_RDMA_JSON="null"
RANK1_RDMA_JSON="null"
if [[ -n "$RANK0_RDMA" ]]; then RANK0_RDMA_JSON="\"$RANK0_RDMA\""; fi
if [[ -n "$RANK1_RDMA" ]]; then RANK1_RDMA_JSON="\"$RANK1_RDMA\""; fi

case "$BACKEND" in
  jaccl|jaccl-ring)
    if ! ssh -o BatchMode=yes -o ConnectTimeout=5 -o ConnectionAttempts=1 \
        "$RANK1_DIRECT_SSH" 'true' >/dev/null 2>&1; then
      if [[ -n "$RANK1_FALLBACK_SSH" ]]; then
        RANK1_SSH="$RANK1_FALLBACK_SSH"
        echo "[launch] WARN: direct SSH to worker unavailable; using fallback SSH control only." >&2
      else
        echo "[launch] ERROR: rank 1 SSH is unreachable and no M3_RANK1_FALLBACK_SSH is set." >&2
        exit 2
      fi
    fi
    # Hostfile separates SSH control plane from distributed data plane:
    # - rank 0 runs locally (127.0.0.1, no ssh needed)
    # - rank 1 may launch over direct SSH or fallback SSH control
    # - JACCL coordinator/IPs/RDMA devices use the configured data link
    cat > "$HOSTFILE" <<EOF
{
  "backend": "$BACKEND",
  "envs": [],
  "hosts": [
    {"ssh": "127.0.0.1", "ips": ["$RANK0_DATA_IP"], "rdma": [null, $RANK0_RDMA_JSON]},
    {"ssh": "$RANK1_SSH", "ips": ["$RANK1_DATA_IP"], "rdma": [$RANK1_RDMA_JSON, null]}
  ]
}
EOF
    LAUNCH_HOST_ARGS=(--hostfile "$HOSTFILE")
    echo "[launch] using $BACKEND hostfile: SSH=local/rank1, data=$RANK0_DATA_IP<->$RANK1_DATA_IP" >&2
    ;;
  ring)
    if [[ -n "${M3_MLX_HOSTS:-}" ]]; then
      HOSTS="$M3_MLX_HOSTS"
    elif ssh -o BatchMode=yes -o ConnectTimeout=5 -o ConnectionAttempts=1 \
        "$RANK1_DIRECT_SSH" 'true' >/dev/null 2>&1; then
      HOSTS="$DIRECT_HOSTS"
    else
      HOSTS="$FALLBACK_HOSTS"
      echo "[launch] WARN: direct rank 1 SSH unavailable; using fallback hosts for ring backend." >&2
    fi
    LAUNCH_HOST_ARGS=(--backend ring --hosts "$HOSTS")
    ;;
  *)
    echo "[launch] ERROR: unsupported M3_MLX_BACKEND=$BACKEND (use jaccl, jaccl-ring, or ring)" >&2
    exit 2
    ;;
esac

if [[ "${MLX_M3_APPLY_RUNTIME_PATCHES:-1}" == "1" ]]; then
  for PATCHER_NAME in \
      apply_mlx_vlm_prefill_progress_patch.py \
      apply_mlx_vlm_prefill_clear_cache_patch.py; do
    PATCHER="$CLUSTER/runtime_patches/$PATCHER_NAME"
    if [[ -f "$PATCHER" ]]; then
      "$PYTHON" "$PATCHER" >&2
      if [[ "$BACKEND" == "jaccl" || "$BACKEND" == "jaccl-ring" ]]; then
        ssh -o BatchMode=yes -o ConnectTimeout=10 "$RANK1_SSH" \
          "cd '$CLUSTER' && '$PYTHON' '$PATCHER'" >&2
      fi
    fi
  done
fi

# PIPELINE parallel over THUNDERBOLT/JACCL by default.
# Production split:
#   Rank 0: final layers, norm, lm_head, and OpenAI API
#   Rank 1: initial layers and embeddings
#
# COMMAND BUFFER SIZING (the GPU-timeout fix):
#   MLX_MAX_OPS_PER_BUFFER / MLX_MAX_MB_PER_BUFFER cap how much work goes into
#   a SINGLE Metal command buffer. If one buffer takes >~10s to execute, the
#   GPU driver kills it (kIOGPUCommandBufferCallbackErrorTimeout -> SIGABRT).
#   This is the REAL root cause that hid behind the watchdog crashes: on the
#   Worker processing a large layer slice can make a large prefill buffer
#   512MB easily exceeded the driver timeout. Smaller buffers (16 ops / 128MB)
#   complete well within the timeout, so async_eval stays enabled (no prefill
#   stall) and no buffer triggers the driver kill. If GPU timeouts return,
#   LOWER memory further (e.g. 2 ops / 16MB) if sustained generation stalls.
exec "$MLX_LAUNCH" \
  "${LAUNCH_HOST_ARGS[@]}" \
  --starting-port 32323 \
  --connections-per-ip 2 \
  --python "$PYTHON" \
  --cwd "$CLUSTER" \
  --env PATH="$CLUSTER/bin:${PATH:-/usr/bin:/bin}" \
  --env PYTHONUNBUFFERED=1 \
  --env M3_SHARDING_MODE="${M3_SHARDING_MODE:-pipeline}" \
  --env M3_PIPELINE_LAYERS="${M3_PIPELINE_LAYERS:-38,22}" \
  --env MLX_M3_MODEL="$MODEL" \
  --env MLX_M3_MODEL_ID="$MODEL_ID" \
  --env MLX_M3_HOST="${MLX_M3_HOST:-0.0.0.0}" \
  --env MLX_M3_PORT="${MLX_M3_PORT:-8080}" \
  --env M3_WATCHDOG_TIMEOUT="${M3_WATCHDOG_TIMEOUT:-2400}" \
  --env M3_WATCHDOG_PREFILL_TIMEOUT="${M3_WATCHDOG_PREFILL_TIMEOUT:-3600}" \
  --env M3_WATCHDOG_DECODE_TIMEOUT="${M3_WATCHDOG_DECODE_TIMEOUT:-180}" \
  --env M3_MAX_GENERATION_SECONDS="${M3_MAX_GENERATION_SECONDS:-7200}" \
  --env M3_SIGNAL_CLEAR_TIMEOUT="${M3_SIGNAL_CLEAR_TIMEOUT:-60}" \
  --env MLX_M3_THINKING_MODE="${MLX_M3_THINKING_MODE:-enabled}" \
  --env MLX_M3_THINKING_RUNAWAY_TOKEN_BUDGET="${MLX_M3_THINKING_RUNAWAY_TOKEN_BUDGET:-8192}" \
  --env MLX_M3_TOOL_THINKING_RUNAWAY_TOKEN_BUDGET="${MLX_M3_TOOL_THINKING_RUNAWAY_TOKEN_BUDGET:-2048}" \
  --env MLX_M3_THINKING_DEFAULT_REPETITION_PENALTY="${MLX_M3_THINKING_DEFAULT_REPETITION_PENALTY:-1.05}" \
  --env MLX_M3_THINKING_MIN_TEMPERATURE="${MLX_M3_THINKING_MIN_TEMPERATURE:-0.5}" \
  --env MLX_M3_DEFAULT_MAX_TOKENS="${MLX_M3_DEFAULT_MAX_TOKENS:-16384}" \
  --env MLX_M3_NONSTREAM_DEFAULT_MAX_TOKENS="${MLX_M3_NONSTREAM_DEFAULT_MAX_TOKENS:-512}" \
  --env MLX_M3_OPENWEBUI_DEFAULT_MAX_TOKENS="${MLX_M3_OPENWEBUI_DEFAULT_MAX_TOKENS:-2048}" \
  --env MLX_M3_DEFAULT_TEMPERATURE="${MLX_M3_DEFAULT_TEMPERATURE:-0.8}" \
  --env MLX_M3_DEFAULT_TOP_P="${MLX_M3_DEFAULT_TOP_P:-1.0}" \
  --env MLX_M3_DEFAULT_TOP_K="${MLX_M3_DEFAULT_TOP_K:-0}" \
  --env MLX_M3_DEFAULT_MIN_P="${MLX_M3_DEFAULT_MIN_P:-0.0}" \
  --env MLX_M3_TOOL_DEFAULT_TEMPERATURE="${MLX_M3_TOOL_DEFAULT_TEMPERATURE:-0}" \
  --env MLX_M3_TOOL_DEFAULT_TOP_P="${MLX_M3_TOOL_DEFAULT_TOP_P:-1.0}" \
  --env MLX_M3_TOOL_DEFAULT_TOP_K="${MLX_M3_TOOL_DEFAULT_TOP_K:-0}" \
  --env MLX_M3_TOOL_DEFAULT_MIN_P="${MLX_M3_TOOL_DEFAULT_MIN_P:-0.0}" \
  --env MLX_M3_TOOL_THINKING_MODE="${MLX_M3_TOOL_THINKING_MODE:-request}" \
  --env MLX_M3_TOOL_COMPAT_OVERLAY="${MLX_M3_TOOL_COMPAT_OVERLAY:-1}" \
  --env MLX_M3_TOOL_SYSTEM_HINT="${MLX_M3_TOOL_SYSTEM_HINT:-0}" \
  --env MLX_M3_INJECT_DATE_CONTEXT="${MLX_M3_INJECT_DATE_CONTEXT:-1}" \
  --env MLX_M3_TOOL_DEFAULT_REPETITION_PENALTY="${MLX_M3_TOOL_DEFAULT_REPETITION_PENALTY:-0}" \
  --env MLX_M3_TOOL_HIDE_NAMES="${MLX_M3_TOOL_HIDE_NAMES:-}" \
  --env MLX_M3_CONSTRAINED_TOOLS="${MLX_M3_CONSTRAINED_TOOLS:-0}" \
  --env JACCL_PROGRESS_TIMEOUT_MS="${JACCL_PROGRESS_TIMEOUT_MS:-30000}" \
  --env JACCL_TIMEOUT_ACTION="${JACCL_TIMEOUT_ACTION:-teardown-exit}" \
  --env MLX_M3_BATCH_CANCEL="${MLX_M3_BATCH_CANCEL:-0}" \
  --env MLX_M3_BATCH_APPEND_RESERVE_TOKENS="${MLX_M3_BATCH_APPEND_RESERVE_TOKENS:-4096}" \
  --env MLX_M3_BATCH_APPEND_RESERVE_TOKENS_RANK0="${MLX_M3_BATCH_APPEND_RESERVE_TOKENS_RANK0:-}" \
  --env MLX_M3_BATCH_APPEND_RESERVE_TOKENS_RANK1="${MLX_M3_BATCH_APPEND_RESERVE_TOKENS_RANK1:-}" \
  --env MLX_M3_EAGLE3_DRAFT="${MLX_M3_EAGLE3_DRAFT:-}" \
  --env MLX_M3_EAGLE3_BLOCK="${MLX_M3_EAGLE3_BLOCK:-0}" \
  --env MLX_M3_EAGLE3_FORCE="${MLX_M3_EAGLE3_FORCE:-0}" \
  --env MLX_M3_EAGLE3_NORM_RESIDUAL="${MLX_M3_EAGLE3_NORM_RESIDUAL:-0}" \
  --env MLX_M3_EAGLE3_CAPTURE_LAYERS="${MLX_M3_EAGLE3_CAPTURE_LAYERS:-}" \
  --env MLX_M3_EAGLE3_DUMP_DIR="${MLX_M3_EAGLE3_DUMP_DIR:-}" \
  --env MLX_M3_EAGLE3_CAPTURE_ONLY="${MLX_M3_EAGLE3_CAPTURE_ONLY:-0}" \
  --env MLX_M3_EAGLE3_CAPTURE_MAX_MB="${MLX_M3_EAGLE3_CAPTURE_MAX_MB:-200}" \
  --env MLX_M3_EAGLE3_CAPTURE_DIR_MAX_GB="${MLX_M3_EAGLE3_CAPTURE_DIR_MAX_GB:-100}" \
  --env MLX_M3_EAGLE3_CAPTURE_EVAL_EVERY="${MLX_M3_EAGLE3_CAPTURE_EVAL_EVERY:-256}" \
  --env MLX_M3_EAGLE3_PIPE_DEBUG="${MLX_M3_EAGLE3_PIPE_DEBUG:-0}" \
  --env MLX_M3_PREFILL_CANCEL_EVERY="${MLX_M3_PREFILL_CANCEL_EVERY:-1}" \
  --env MLX_M3_KEEP_CACHE_ON_CANCEL="${MLX_M3_KEEP_CACHE_ON_CANCEL:-1}" \
  --env MLX_M3_TOOL_UNUSABLE_RETRY_ATTEMPTS="${MLX_M3_TOOL_UNUSABLE_RETRY_ATTEMPTS:-2}" \
  --env MLX_M3_TOOL_UNUSABLE_RETRY_TEMPERATURES="${MLX_M3_TOOL_UNUSABLE_RETRY_TEMPERATURES:-0.2,0.3}" \
  --env MLX_M3_TOOL_UNUSABLE_RETRY_MAX_TOKENS="${MLX_M3_TOOL_UNUSABLE_RETRY_MAX_TOKENS:-8192}" \
  --env MLX_M3_TOOL_RETRY_NO_THINK="${MLX_M3_TOOL_RETRY_NO_THINK:-1}" \
  --env MLX_M3_TOOL_RETRY_NO_THINK_MAX_PROMPT_TOKENS="${MLX_M3_TOOL_RETRY_NO_THINK_MAX_PROMPT_TOKENS:-16384}" \
  --env MLX_M3_TOOL_WRITE_CHUNK_MAX_CHARS="${MLX_M3_TOOL_WRITE_CHUNK_MAX_CHARS:-6000}" \
  --env MLX_M3_TOOL_WRITE_CHUNK_TARGET_CHARS="${MLX_M3_TOOL_WRITE_CHUNK_TARGET_CHARS:-4096}" \
  --env MLX_M3_TOOL_INCOMPLETE_CALL_TOKEN_BUDGET="${MLX_M3_TOOL_INCOMPLETE_CALL_TOKEN_BUDGET:-8192}" \
  --env MLX_M3_TOOL_NO_CALL_TOKEN_BUDGET="${MLX_M3_TOOL_NO_CALL_TOKEN_BUDGET:-768}" \
  --env MLX_M3_TOOL_ACTION_NO_CALL_TOKEN_BUDGET="${MLX_M3_TOOL_ACTION_NO_CALL_TOKEN_BUDGET:-1536}" \
  --env MLX_M3_TOOL_RETRY_NO_CALL_TOKEN_BUDGET="${MLX_M3_TOOL_RETRY_NO_CALL_TOKEN_BUDGET:-384}" \
  --env MLX_M3_BATCH_TOOL_NATURAL_DRAIN="${MLX_M3_BATCH_TOOL_NATURAL_DRAIN:-1}" \
  --env MLX_M3_TOOL_LOOP_STEER_MAX_TOOL_ONLY_TURNS="${MLX_M3_TOOL_LOOP_STEER_MAX_TOOL_ONLY_TURNS:-0}" \
  --env MLX_M3_TOOL_LOOP_STEER_MAX_REPEATED_TOOL="${MLX_M3_TOOL_LOOP_STEER_MAX_REPEATED_TOOL:-0}" \
  --env MLX_M3_TOOL_LOOP_STEER_MAX_REPEATED_COMMANDS="${MLX_M3_TOOL_LOOP_STEER_MAX_REPEATED_COMMANDS:-0}" \
  --env MLX_M3_TOOL_LOOP_FORCE_FINAL_AFTER="${MLX_M3_TOOL_LOOP_FORCE_FINAL_AFTER:-0}" \
  --env MLX_M3_TOOL_LOOP_FORCE_FINAL_REPEATED_COMMANDS="${MLX_M3_TOOL_LOOP_FORCE_FINAL_REPEATED_COMMANDS:-0}" \
  --env MLX_M3_TOOL_LOOP_FORCE_FINAL_IDENTICAL_COMMAND_RESULTS="${MLX_M3_TOOL_LOOP_FORCE_FINAL_IDENTICAL_COMMAND_RESULTS:-4}" \
  --env MLX_M3_TOOL_LOOP_FORCE_FINAL_REPEATED_TOOL_COUNT="${MLX_M3_TOOL_LOOP_FORCE_FINAL_REPEATED_TOOL_COUNT:-0}" \
  --env MLX_M3_TOOL_LOOP_FORCE_FINAL_REPEATED_TOOL_NAMES="${MLX_M3_TOOL_LOOP_FORCE_FINAL_REPEATED_TOOL_NAMES:-}" \
  --env MLX_M3_TOOL_LOOP_FILTER_REPEATED_WORK_TOOLS="${MLX_M3_TOOL_LOOP_FILTER_REPEATED_WORK_TOOLS:-}" \
  --env MLX_M3_FORCE_NO_THINKING_FOR_TOOLS="${MLX_M3_FORCE_NO_THINKING_FOR_TOOLS:-0}" \
  --env MLX_M3_EMIT_TOOL_REASONING="${MLX_M3_EMIT_TOOL_REASONING:-1}" \
  --env MLX_M3_DEFAULT_REPETITION_PENALTY="${MLX_M3_DEFAULT_REPETITION_PENALTY:-0}" \
  --env MLX_M3_DEFAULT_PRESENCE_PENALTY="${MLX_M3_DEFAULT_PRESENCE_PENALTY:-0}" \
  --env MLX_M3_DEFAULT_FREQUENCY_PENALTY="${MLX_M3_DEFAULT_FREQUENCY_PENALTY:-0}" \
  --env MLX_M3_DEFAULT_SEED="${MLX_M3_DEFAULT_SEED:-1}" \
  --env MLX_M3_TOOL_DEFAULT_SEED="${MLX_M3_TOOL_DEFAULT_SEED:-${MLX_M3_DEFAULT_SEED:-1}}" \
  --env MLX_M3_THINKING_BUDGET="${MLX_M3_THINKING_BUDGET:-0}" \
  --env MLX_M3_ALLOW_THINKING_BUDGET="${MLX_M3_ALLOW_THINKING_BUDGET:-0}" \
  --env MLX_M3_STREAM_MODE="${MLX_M3_STREAM_MODE:-buffered}" \
  --env MLX_M3_MAX_CONCURRENT_REQUESTS="${MLX_M3_MAX_CONCURRENT_REQUESTS:-1}" \
  --env MLX_M3_REQUEST_HISTORY_MAX="${MLX_M3_REQUEST_HISTORY_MAX:-32}" \
  --env MLX_M3_DECODE_EVAL_EVERY="${MLX_M3_DECODE_EVAL_EVERY:-4}" \
  --env MLX_M3_DECODE_EVAL_AFTER_TOKENS="${MLX_M3_DECODE_EVAL_AFTER_TOKENS:-96}" \
  --env MLX_M3_DECODE_EVAL_AFTER_EVERY="${MLX_M3_DECODE_EVAL_AFTER_EVERY:-1}" \
  --env MLX_M3_THINKING_DECODE_EVAL_EVERY="${MLX_M3_THINKING_DECODE_EVAL_EVERY:-1}" \
  --env MLX_M3_THINKING_RAW_SILENT_LIMIT="${MLX_M3_THINKING_RAW_SILENT_LIMIT:-32}" \
  --env MLX_M3_LONG_CONTEXT_DECODE_EVAL_TOKENS="${MLX_M3_LONG_CONTEXT_DECODE_EVAL_TOKENS:-24576}" \
  --env MLX_M3_LONG_CONTEXT_DECODE_EVAL_EVERY="${MLX_M3_LONG_CONTEXT_DECODE_EVAL_EVERY:-1}" \
  --env MLX_M3_ADAPTIVE_LONG_CONTEXT_DECODE_EVAL="${MLX_M3_ADAPTIVE_LONG_CONTEXT_DECODE_EVAL:-0}" \
  --env MLX_M3_MID_CONTEXT_DECODE_EVAL_TOKENS="${MLX_M3_MID_CONTEXT_DECODE_EVAL_TOKENS:-24576}" \
  --env MLX_M3_MID_CONTEXT_DECODE_EVAL_EVERY="${MLX_M3_MID_CONTEXT_DECODE_EVAL_EVERY:-1}" \
  --env MLX_M3_HIGH_CONTEXT_DECODE_EVAL_TOKENS="${MLX_M3_HIGH_CONTEXT_DECODE_EVAL_TOKENS:-98304}" \
  --env MLX_M3_HIGH_CONTEXT_DECODE_EVAL_EVERY="${MLX_M3_HIGH_CONTEXT_DECODE_EVAL_EVERY:-1}" \
  --env MLX_M3_ALLOW_UNSAFE_RUNTIME_TUNING="${MLX_M3_ALLOW_UNSAFE_RUNTIME_TUNING:-0}" \
  --env MLX_M3_REFRESH_GENERATION_STREAM="${MLX_M3_REFRESH_GENERATION_STREAM:-0}" \
  --env MLX_M3_SYNC_SAMPLED_TOKENS="${MLX_M3_SYNC_SAMPLED_TOKENS:-1}" \
  --env MLX_M3_RANK0_ONLY_LOGITS="${MLX_M3_RANK0_ONLY_LOGITS:-1}" \
  --env MLX_M3_RANK0_DECODE_OWNER="${MLX_M3_RANK0_DECODE_OWNER:-1}" \
  --env MLX_M3_RANK1_SSH="$RANK1_SSH" \
  --env MLX_M3_ENABLE_UNSAFE_INFLIGHT_STOP="${MLX_M3_ENABLE_UNSAFE_INFLIGHT_STOP:-1}" \
  --env MLX_M3_STOP_ON_CLIENT_DISCONNECT="${MLX_M3_STOP_ON_CLIENT_DISCONNECT:-1}" \
  --env MLX_M3_STOP_CHECK_EVERY="${MLX_M3_STOP_CHECK_EVERY:-4}" \
  --env MLX_M3_PREFILL_STOP_CHECK_EVERY="${MLX_M3_PREFILL_STOP_CHECK_EVERY:-1}" \
  --env MLX_M3_PREFILL_STOP_FILE="${MLX_M3_PREFILL_STOP_FILE:-/private/tmp/minimax_m3_prefill_stop_requested}" \
  --env MLX_M3_SSE_KEEPALIVE_SECONDS="${MLX_M3_SSE_KEEPALIVE_SECONDS:-5}" \
  --env MLX_M3_TOOL_STREAM_PROGRESS_SECONDS="${MLX_M3_TOOL_STREAM_PROGRESS_SECONDS:-45}" \
  --env MLX_M3_IMAGE_DEFAULT_MAX_TOKENS="${MLX_M3_IMAGE_DEFAULT_MAX_TOKENS:-768}" \
  --env MLX_M3_IMAGE_MAX_TOKENS="${MLX_M3_IMAGE_MAX_TOKENS:-0}" \
  --env MLX_M3_WIRED_LIMIT_GB="${MLX_M3_WIRED_LIMIT_GB:-0}" \
  --env MLX_M3_WIRED_LIMIT_GB_RANK0="${MLX_M3_WIRED_LIMIT_GB_RANK0:-${MLX_M3_WIRED_LIMIT_GB:-0}}" \
  --env MLX_M3_WIRED_LIMIT_GB_RANK1="${MLX_M3_WIRED_LIMIT_GB_RANK1:-${MLX_M3_WIRED_LIMIT_GB:-0}}" \
  --env MLX_M3_CACHE_LIMIT_GB="${MLX_M3_CACHE_LIMIT_GB:-32}" \
  --env MLX_TRUST_REMOTE_CODE=true \
  --env MLX_METAL_FAST_SYNCH="${MLX_METAL_FAST_SYNCH:-1}" \
  --env MLX_MAX_OPS_PER_BUFFER="${MLX_MAX_OPS_PER_BUFFER:-16}" \
  --env MLX_MAX_MB_PER_BUFFER="${MLX_MAX_MB_PER_BUFFER:-512}" \
  --env MLX_M3_PREFILL_STEP_SIZE="${MLX_M3_PREFILL_STEP_SIZE:-4096}" \
  --env MLX_M3_PREFILL_CLEAR_CACHE_EVERY="${MLX_M3_PREFILL_CLEAR_CACHE_EVERY:-0}" \
  --env MLX_M3_PREFILL_ASYNC_OVERLAP="${MLX_M3_PREFILL_ASYNC_OVERLAP:-0}" \
  --env MLX_M3_PREFILL_OVERLAP_NATIVE="${MLX_M3_PREFILL_OVERLAP_NATIVE:-0}" \
  --env MLX_M3_TOOL_STREAM_CONTENT="${MLX_M3_TOOL_STREAM_CONTENT:-0}" \
  --env MLX_M3_TOOL_STREAM_HOLDBACK_CHARS="${MLX_M3_TOOL_STREAM_HOLDBACK_CHARS:-24}" \
  --env MLX_M3_SAFE_DECODE_STOP="${MLX_M3_SAFE_DECODE_STOP:-0}" \
  --env MLX_M3_MAX_KV_SIZE="${MLX_M3_MAX_KV_SIZE:-1000000}" \
  --env MLX_M3_ADVERTISED_MAX_MODEL_LEN="${MLX_M3_ADVERTISED_MAX_MODEL_LEN:-300000}" \
  --env MLX_M3_HARD_MAX_INPUT_TOKENS="${MLX_M3_HARD_MAX_INPUT_TOKENS:-0}" \
  --env MLX_M3_KV_QUANT_ENABLED="${MLX_M3_KV_QUANT_ENABLED:-0}" \
  --env MLX_M3_KV_BITS="${MLX_M3_KV_BITS:-4}" \
  --env MLX_M3_KV_GROUP_SIZE="${MLX_M3_KV_GROUP_SIZE:-64}" \
  --env MLX_M3_KV_QUANT_SCHEME="${MLX_M3_KV_QUANT_SCHEME:-uniform}" \
  --env MLX_M3_QUANTIZED_KV_START="${MLX_M3_QUANTIZED_KV_START:-5000}" \
  --env MLX_M3_PROMPT_CACHE="${MLX_M3_PROMPT_CACHE:-1}" \
  --env MLX_M3_PROMPT_CACHE_THINKING="${MLX_M3_PROMPT_CACHE_THINKING:-1}" \
  --env MLX_M3_PROMPT_CACHE_THINKING_MODE="$THINKING_CACHE_MODE" \
  --env MLX_M3_PROMPT_CACHE_DIRECT_SUFFIX_IDS="${MLX_M3_PROMPT_CACHE_DIRECT_SUFFIX_IDS:-0}" \
  --env MLX_M3_PROMPT_CACHE_MIN_REUSE="${MLX_M3_PROMPT_CACHE_MIN_REUSE:-32}" \
  --env MLX_M3_PROMPT_CACHE_MIN_SUFFIX_TOKENS="${MLX_M3_PROMPT_CACHE_MIN_SUFFIX_TOKENS:-128}" \
  --env MLX_M3_PROMPT_CACHE_FAST_MIN_SUFFIX_TOKENS="${MLX_M3_PROMPT_CACHE_FAST_MIN_SUFFIX_TOKENS:-1}" \
  --env MLX_M3_PROMPT_CACHE_FAST_THINKING_MIN_SUFFIX_TOKENS="${MLX_M3_PROMPT_CACHE_FAST_THINKING_MIN_SUFFIX_TOKENS:-64}" \
  --env MLX_M3_PROMPT_CACHE_REUSE_BUCKET_TOKENS="${MLX_M3_PROMPT_CACHE_REUSE_BUCKET_TOKENS:-0}" \
  --env MLX_M3_REASONING_RECALL="${MLX_M3_REASONING_RECALL:-1}" \
  --env MLX_M3_REASONING_RECALL_MAX_SESSIONS="${MLX_M3_REASONING_RECALL_MAX_SESSIONS:-16}" \
  --env MLX_M3_REASONING_RECALL_MAX_ITEMS="${MLX_M3_REASONING_RECALL_MAX_ITEMS:-64}" \
  --env MLX_M3_REASONING_RECALL_MAX_CHARS="${MLX_M3_REASONING_RECALL_MAX_CHARS:-65536}" \
  --env MLX_M3_PROMPT_CACHE_TTL_SECONDS="${MLX_M3_PROMPT_CACHE_TTL_SECONDS:-10800}" \
  --env MLX_M3_PROMPT_CACHE_MAX_TOKENS="${MLX_M3_PROMPT_CACHE_MAX_TOKENS:-0}" \
  --env MLX_M3_PROMPT_CACHE_GENERATED_REUSE_MAX_TOKENS="${MLX_M3_PROMPT_CACHE_GENERATED_REUSE_MAX_TOKENS:-4096}" \
  --env MLX_M3_PROMPT_CACHE_PROTECT_LARGE="${MLX_M3_PROMPT_CACHE_PROTECT_LARGE:-1}" \
  --env MLX_M3_PROMPT_CACHE_PROTECT_MIN_TOKENS="${MLX_M3_PROMPT_CACHE_PROTECT_MIN_TOKENS:-32768}" \
  --env MLX_M3_PROMPT_CACHE_PROTECT_BYPASS_MAX_TOKENS="${MLX_M3_PROMPT_CACHE_PROTECT_BYPASS_MAX_TOKENS:-8192}" \
  --env MLX_M3_PROMPT_CACHE_SESSION_PROTECT="${MLX_M3_PROMPT_CACHE_SESSION_PROTECT:-1}" \
  --env MLX_M3_PROMPT_CACHE_SESSION_PROTECT_MIN_TOKENS="${MLX_M3_PROMPT_CACHE_SESSION_PROTECT_MIN_TOKENS:-256}" \
  --env MLX_M3_PROMPT_CACHE_SESSION_PROTECT_BYPASS_MAX_TOKENS="${MLX_M3_PROMPT_CACHE_SESSION_PROTECT_BYPASS_MAX_TOKENS:-8192}" \
  --env MLX_M3_PROMPT_CACHE_STATIC_PREFIX_REBUILD_MAX_TOKENS="${MLX_M3_PROMPT_CACHE_STATIC_PREFIX_REBUILD_MAX_TOKENS:-512}" \
  --env MLX_M3_PROMPT_CACHE_STATIC_PREFIX_REBUILD_MAX_REUSE_RATIO="${MLX_M3_PROMPT_CACHE_STATIC_PREFIX_REBUILD_MAX_REUSE_RATIO:-0.80}" \
  --env MLX_M3_PROMPT_CACHE_SMALL_THINKING_REBUILD_MAX_TOKENS="${MLX_M3_PROMPT_CACHE_SMALL_THINKING_REBUILD_MAX_TOKENS:-0}" \
  --env MLX_M3_PROMPT_CACHE_SMALL_THINKING_REBUILD_MAX_SUFFIX_TOKENS="${MLX_M3_PROMPT_CACHE_SMALL_THINKING_REBUILD_MAX_SUFFIX_TOKENS:-0}" \
  --env MLX_M3_PROMPT_CACHE_SESSION_MAP_MAX="${MLX_M3_PROMPT_CACHE_SESSION_MAP_MAX:-16}" \
  --env MLX_M3_PROMPT_CACHE_RESIDENT_SLOTS="${MLX_M3_PROMPT_CACHE_RESIDENT_SLOTS:-4}" \
  --env MLX_M3_PROMPT_CACHE_RESIDENT_MAX_TOTAL_TOKENS_RANK1="${MLX_M3_PROMPT_CACHE_RESIDENT_MAX_TOTAL_TOKENS_RANK1:-200000}" \
  --env MLX_M3_PROMPT_CACHE_RESIDENT_MAX_TOTAL_TOKENS="${MLX_M3_PROMPT_CACHE_RESIDENT_MAX_TOTAL_TOKENS:-750000}" \
  --env MLX_M3_PROMPT_CACHE_SESSION_MANIFEST="${MLX_M3_PROMPT_CACHE_SESSION_MANIFEST:-1}" \
  --env MLX_M3_PROMPT_CACHE_SESSION_MANIFEST_MAX="${MLX_M3_PROMPT_CACHE_SESSION_MANIFEST_MAX:-64}" \
  --env MLX_M3_PROMPT_CACHE_SESSION_MANIFEST_PATH="${MLX_M3_PROMPT_CACHE_SESSION_MANIFEST_PATH:-$CLUSTER/prompt_cache_sessions.json}" \
  --env MLX_M3_PROMPT_CACHE_SSD="${MLX_M3_PROMPT_CACHE_SSD:-0}" \
  --env MLX_M3_PROMPT_CACHE_SSD_RESTORE="${MLX_M3_PROMPT_CACHE_SSD_RESTORE:-0}" \
  --env MLX_M3_PROMPT_CACHE_SSD_AUTO_SAVE="${MLX_M3_PROMPT_CACHE_SSD_AUTO_SAVE:-0}" \
  --env MLX_M3_PROMPT_CACHE_SSD_AUTO_SAVE_MIN_DELTA_TOKENS="${MLX_M3_PROMPT_CACHE_SSD_AUTO_SAVE_MIN_DELTA_TOKENS:-8192}" \
  --env MLX_M3_PROMPT_CACHE_SSD_APPEND_RESERVE_TOKENS="${MLX_M3_PROMPT_CACHE_SSD_APPEND_RESERVE_TOKENS:-4096}" \
  --env MLX_M3_PROMPT_CACHE_SSD_APPEND_RESERVE_TOKENS_RANK0="${MLX_M3_PROMPT_CACHE_SSD_APPEND_RESERVE_TOKENS_RANK0:-}" \
  --env MLX_M3_PROMPT_CACHE_SSD_APPEND_RESERVE_TOKENS_RANK1="${MLX_M3_PROMPT_CACHE_SSD_APPEND_RESERVE_TOKENS_RANK1:-}" \
  --env MLX_M3_PROMPT_CACHE_SSD_SAVE_RESERVE_TOKENS="${MLX_M3_PROMPT_CACHE_SSD_SAVE_RESERVE_TOKENS:-0}" \
  --env MLX_M3_PROMPT_CACHE_SSD_SAVE_RESERVE_TOKENS_RANK0="${MLX_M3_PROMPT_CACHE_SSD_SAVE_RESERVE_TOKENS_RANK0:-}" \
  --env MLX_M3_PROMPT_CACHE_SSD_SAVE_RESERVE_TOKENS_RANK1="${MLX_M3_PROMPT_CACHE_SSD_SAVE_RESERVE_TOKENS_RANK1:-}" \
  --env MLX_M3_PROMPT_CACHE_SSD_DIR="${MLX_M3_PROMPT_CACHE_SSD_DIR:-$HOME/.cache/thundermlx/prompt-kv}" \
  --env MLX_M3_PROMPT_CACHE_SSD_DIR_RANK0="${MLX_M3_PROMPT_CACHE_SSD_DIR_RANK0:-}" \
  --env MLX_M3_PROMPT_CACHE_SSD_DIR_RANK1="${MLX_M3_PROMPT_CACHE_SSD_DIR_RANK1:-}" \
  --env MLX_M3_PROMPT_CACHE_SSD_TTL_SECONDS="${MLX_M3_PROMPT_CACHE_SSD_TTL_SECONDS:-432000}" \
  --env MLX_M3_PROMPT_CACHE_SSD_MAX_BYTES="${MLX_M3_PROMPT_CACHE_SSD_MAX_BYTES:-429496729600}" \
  --env MLX_M3_PROMPT_CACHE_SSD_MIN_TOKENS="${MLX_M3_PROMPT_CACHE_SSD_MIN_TOKENS:-8192}" \
  --env MLX_M3_PROMPT_CACHE_SSD_STATUS_SCAN_INTERVAL_SECONDS="${MLX_M3_PROMPT_CACHE_SSD_STATUS_SCAN_INTERVAL_SECONDS:-10}" \
  --env MLX_M3_PROMPT_CACHE_SSD_SAVE_REASONING="${MLX_M3_PROMPT_CACHE_SSD_SAVE_REASONING:-0}" \
  --env MLX_M3_PROMPT_CACHE_SSD_PRIVACY="${MLX_M3_PROMPT_CACHE_SSD_PRIVACY:-local}" \
  --env MLX_M3_PROMPT_CACHE_KEEPWARM="${MLX_M3_PROMPT_CACHE_KEEPWARM:-0}" \
  --env MLX_M3_PROMPT_CACHE_KEEPWARM_MODE="${MLX_M3_PROMPT_CACHE_KEEPWARM_MODE:-metal}" \
  --env MLX_M3_PROMPT_CACHE_KEEPWARM_INTERVAL_SECONDS="${MLX_M3_PROMPT_CACHE_KEEPWARM_INTERVAL_SECONDS:-5}" \
  --env MLX_M3_PROMPT_CACHE_KEEPWARM_IDLE_AFTER_SECONDS="${MLX_M3_PROMPT_CACHE_KEEPWARM_IDLE_AFTER_SECONDS:-3}" \
  --env MLX_M3_PROMPT_CACHE_KEEPWARM_MATRIX_SIZE="${MLX_M3_PROMPT_CACHE_KEEPWARM_MATRIX_SIZE:-1}" \
  --env MLX_M3_PROMPT_CACHE_KEEPWARM_LARGE_CACHE_TOKENS="${MLX_M3_PROMPT_CACHE_KEEPWARM_LARGE_CACHE_TOKENS:-8192}" \
  --env MLX_M3_PROMPT_CACHE_KEEPWARM_LARGE_INTERVAL_SECONDS="${MLX_M3_PROMPT_CACHE_KEEPWARM_LARGE_INTERVAL_SECONDS:-5}" \
  --env MLX_M3_PROMPT_CACHE_KEEPWARM_SLOW_BACKOFF_SECONDS="${MLX_M3_PROMPT_CACHE_KEEPWARM_SLOW_BACKOFF_SECONDS:-0}" \
  --env MLX_M3_PROMPT_CACHE_REQUEST_START_KEEPWARM="${MLX_M3_PROMPT_CACHE_REQUEST_START_KEEPWARM:-0}" \
  --env MLX_M3_PROMPT_CACHE_REQUEST_START_KEEPWARM_IDLE_SECONDS="${MLX_M3_PROMPT_CACHE_REQUEST_START_KEEPWARM_IDLE_SECONDS:-2}" \
  --env MLX_M3_PROMPT_CACHE_REQUEST_START_KEEPWARM_MATRIX_SIZE="${MLX_M3_PROMPT_CACHE_REQUEST_START_KEEPWARM_MATRIX_SIZE:-128}" \
  --env MLX_M3_PROMPT_CACHE_REQUEST_START_KEEPWARM_REPEATS="${MLX_M3_PROMPT_CACHE_REQUEST_START_KEEPWARM_REPEATS:-1}" \
  --env MLX_M3_PROMPT_CACHE_POST_RESPONSE_KEEPWARM="${MLX_M3_PROMPT_CACHE_POST_RESPONSE_KEEPWARM:-0}" \
  --env MLX_M3_PROMPT_CACHE_POST_RESPONSE_KEEPWARM_DELAY_SECONDS="${MLX_M3_PROMPT_CACHE_POST_RESPONSE_KEEPWARM_DELAY_SECONDS:-5}" \
  --env MLX_M3_PROMPT_CACHE_POST_RESPONSE_KEEPWARM_MATRIX_SIZE="${MLX_M3_PROMPT_CACHE_POST_RESPONSE_KEEPWARM_MATRIX_SIZE:-128}" \
  --env MLX_M3_PROMPT_CACHE_POST_RESPONSE_KEEPWARM_REPEATS="${MLX_M3_PROMPT_CACHE_POST_RESPONSE_KEEPWARM_REPEATS:-1}" \
  --env MLX_M3_CLEAR_CACHE_AFTER_REQUEST="${MLX_M3_CLEAR_CACHE_AFTER_REQUEST:-0}" \
  --env MLX_M3_CLEAR_CACHE_AFTER_ERROR="${MLX_M3_CLEAR_CACHE_AFTER_ERROR:-1}" \
  --env MLX_M3_VISIBLE_TRANSCRIPT_PREWARM="${MLX_M3_VISIBLE_TRANSCRIPT_PREWARM:-1}" \
  --env MLX_M3_VISIBLE_TRANSCRIPT_PREWARM_BLOCKING="${MLX_M3_VISIBLE_TRANSCRIPT_PREWARM_BLOCKING:-1}" \
  --env MLX_M3_VISIBLE_TRANSCRIPT_PREWARM_MIN_GENERATED="${MLX_M3_VISIBLE_TRANSCRIPT_PREWARM_MIN_GENERATED:-1}" \
  --env MLX_M3_VISIBLE_TRANSCRIPT_PREWARM_MAX_TOKENS="${MLX_M3_VISIBLE_TRANSCRIPT_PREWARM_MAX_TOKENS:-8192}" \
  --env MLX_M3_VISIBLE_TRANSCRIPT_PREWARM_MAX_SUFFIX_TOKENS="${MLX_M3_VISIBLE_TRANSCRIPT_PREWARM_MAX_SUFFIX_TOKENS:-4096}" \
  --env MLX_M3_VISIBLE_TRANSCRIPT_PREWARM_MAX_GENERATED_TOKENS="${MLX_M3_VISIBLE_TRANSCRIPT_PREWARM_MAX_GENERATED_TOKENS:-4096}" \
  --env MLX_M3_MAX_TOKENS_CEILING="${MLX_M3_MAX_TOKENS_CEILING:-16384}" \
  --env MLX_M3_KV_CACHE_STEP="${MLX_M3_KV_CACHE_STEP:-4096}" \
  --env MLX_M3_LAYER_EVAL_EVERY="${MLX_M3_LAYER_EVAL_EVERY:-0}" \
  --env MLX_M3_OMLX_MINIMAX_OVERLAY="${MLX_M3_OMLX_MINIMAX_OVERLAY:-1}" \
  --env MLX_MINIMAX_MSA_NATIVE_TOPK="${MLX_MINIMAX_MSA_NATIVE_TOPK:-auto}" \
  --env MLX_MINIMAX_MSA_NATIVE_TOPK_RANK0="${MLX_MINIMAX_MSA_NATIVE_TOPK_RANK0:-}" \
  --env MLX_MINIMAX_MSA_NATIVE_TOPK_RANK1="${MLX_MINIMAX_MSA_NATIVE_TOPK_RANK1:-}" \
  --env MLX_M3_DISABLE_SPARSE_INDEX="${MLX_M3_DISABLE_SPARSE_INDEX:-0}" \
  --env MLX_M3_KERNEL_STATS="${MLX_M3_KERNEL_STATS:-0}" \
  --env MLX_M3_MSA_K1_IMPL="${MLX_M3_MSA_K1_IMPL:-auto}" \
  --env MLX_M3_MSA_K1_LONG_CONTEXT_AUTO="${MLX_M3_MSA_K1_LONG_CONTEXT_AUTO:-1}" \
  --env MLX_M3_MSA_K1_LONG_CONTEXT_MIN_TOTAL_K="${MLX_M3_MSA_K1_LONG_CONTEXT_MIN_TOTAL_K:-65536}" \
  --env MLX_M3_MSA_PREFILL_BLOCKWISE_TOPK_MIN_KV_LEN="${MLX_M3_MSA_PREFILL_BLOCKWISE_TOPK_MIN_KV_LEN:-32768}" \
  --env MLX_M3_MSA_PREFILL_BLOCKWISE_TOPK_BLOCK_CHUNK="${MLX_M3_MSA_PREFILL_BLOCKWISE_TOPK_BLOCK_CHUNK:-2}" \
  --env MLX_M3_MSA_PREFILL_LONG_K_SMALL_L_MAX_L="${MLX_M3_MSA_PREFILL_LONG_K_SMALL_L_MAX_L:-0}" \
  --env MLX_M3_MSA_PREFILL_LONG_K_SMALL_L_MIN_KV="${MLX_M3_MSA_PREFILL_LONG_K_SMALL_L_MIN_KV:-32768}" \
  --env MLX_M3_COMPACT_DECODE_SORT_TOPK="${MLX_M3_COMPACT_DECODE_SORT_TOPK:-0}" \
  --env MLX_M3_DECODE_TOPK_REUSE_TOKENS="${MLX_M3_DECODE_TOPK_REUSE_TOKENS:-48}" \
  --env MLX_M3_SPARSE_TOPK_BLOCKS_OVERRIDE="${MLX_M3_SPARSE_TOPK_BLOCKS_OVERRIDE:-16}" \
  --env MLX_M3_SPARSE_DECODE_MIN_FACTOR="${MLX_M3_SPARSE_DECODE_MIN_FACTOR:-64}" \
  --env MLX_M3_SPARSE_DECODE_MIN_FACTOR_MASKED="${MLX_M3_SPARSE_DECODE_MIN_FACTOR_MASKED:-16}" \
  --env MLX_M3_SPLIT_VERIFY="${MLX_M3_SPLIT_VERIFY:-0}" \
  --env MLX_M3_SPLIT_VERIFY_IMPL="${MLX_M3_SPLIT_VERIFY_IMPL:-gather}" \
  --env MLX_M3_SPLIT_VERIFY_MIN_L="${MLX_M3_SPLIT_VERIFY_MIN_L:-2}" \
  --env MLX_M3_SPLIT_VERIFY_MAX_L="${MLX_M3_SPLIT_VERIFY_MAX_L:-8}" \
  --env MLX_M3_FUSED_SPARSE_DECODE="${MLX_M3_FUSED_SPARSE_DECODE:-0}" \
  --env MLX_M3_FUSED_SPARSE_DECODE_MIN_KV="${MLX_M3_FUSED_SPARSE_DECODE_MIN_KV:-6144}" \
  --env MLX_M3_USE_DIRECT_DECODE_KERNEL="${MLX_M3_USE_DIRECT_DECODE_KERNEL:-0}" \
  --env MLX_M3_DIRECT_DECODE_EVAL_MODE="${MLX_M3_DIRECT_DECODE_EVAL_MODE:-small}" \
  --env HF_HUB_OFFLINE="${HF_HUB_OFFLINE:-1}" \
  -- \
  "$LAUNCHER"
# NOTE: launcher-generation compatibility. Old mlx.launch (<=0.31.x lineage,
# incl. the EXO fork) wraps the command with --python: `$PYTHON $LAUNCHER`.
# New mlx.launch (0.32-dev main) execs the command raw and ignores --python.
# Passing the bare script works under BOTH because run_with_watchdog.py is +x,
# uses `#!/usr/bin/env mlx-python`, and this launch exports the synchronized
# project `bin/` directory first on PATH for each rank.
# Never put "$PYTHON" into the command itself — old launchers double-wrap it
# into `python python script` (SyntaxError \xca = Mach-O magic as source).
